name: product-recommendation-intel
channels:
  - intel
  - defaults
dependencies:
  - daal4py=2021.7.0
  - intelpython=2022.2.0
  - numpy=1.21.4
  - pip=21.2.4
  - python=3.9.7
  - scikit-learn-intelex=2021.7.0
  - pip:
    - ipython==8.5.0
    - pandas==1.4.2
    

